language: python
sudo: false
python:
- 3.6
- 3.7

before_script:  # code coverage tool
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
- python -m pip install -r requirements.txt

script:
- python travis_test.py
- coverage run travis_test.py

after_success:
  - codecov

after_script:
  - coverage xml
  - if [[ "$TRAVIS_PULL_REQUEST" == "false"]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

env:
  global:
    - CC_TEST_REPORTER_ID=e1d188936ed92870f8ed42529b4c235f31a7136924e5a13210522d744721b635