env:
  global:
    - CC_TEST_REPORTER_ID=e1d188936ed92870f8ed42529b4c235f31a7136924e5a13210522d744721b635

language: python
os:
  - linux

python:
- 3.6
- 3.7

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
- python -m pip install -r requirements.txt

script:
- coverage run travis_test.py

after_success:
  - codecov

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - coverage xml
