language: python
sudo: false
python:
- 3.5
- 3.6
- 3.7

install:
- python -m pip install -r requirements.txt

script:
- python travis_test.py

after_success:
  - bash <(curl -s https://codecov.io/bash)