language: python
sudo: false
python:
- 3.6
- 3.7

install:
- python -m pip install -r requirements.txt

script:
- python travis_test.py
- coverage run travis_test.py

after_success:
  - codecov